### ISSUE TITLE
SyntaxError: Identifier 'loader' has already been declared when import contains named export `loader`

### ISSUE THREAD

**Issue by lb-** [forge42dev/react-router-devtools#167]
On the path to migrating to Remix, I have run into a really odd error that I have been able to track down to the usage of `react-router-devtools` in combination with a module import that contains a named export `loader`.

I have no idea why this would be happening and the stack trace does not indicate at all that this would be related to the devtools plugin, but removing the plugin stops the error. OR, changing the named export to something other than `loader` (e.g. `getData`) also stops the error.

I hope that you can help us get to the bottom of this, while we can rename a lot of things, it probably indicates a more sinister problem under the hood.

## Steps to reproduce

1. `npx create-react-router@latest my-react-router-app`
2. `cd my-react-router-app`
3. `npm install react-router-devtools -D`
4. `npm run dev` (ensure the application runs)
5. Add a `loader` to the `home` route module `app/routes/home.tsx`
```diff
import type { Route } from "./+types/home";
import { Welcome } from "../welcome/welcome";

+export const loader = async () => {
+  return { data: "example" };
+};

export function meta({}: Route.MetaArgs) {
  return [
    { title: "New React Router App" },
    { name: "description", content: "Welcome to React Router!" },
  ];
}

+export default function Home({ loaderData }: Route.ComponentProps) {
+  return (
+    <div>
+      {loaderData.data}
+      <Welcome />
+    </div>
+  );
+}
```
6. `npm run dev` (ensure the application runs)
7. Abstract the loader method to an external file
```ts
// new file - app/utils/example.ts
export const loader = async () => {
  return { data: "example" };
};
```
8. Update the home route to import and use the extracted loader
```diff
import type { Route } from "./+types/home";
+import * as data from "~/utils/example";
import { Welcome } from "../welcome/welcome";

export const loader = async () => {
-  return { data: "example" };
+  return await data.loader();
};
```
9. `npm run dev` (ensure the application runs)
10. Add the `reactRouterDevTools` plugin now as per the documented instructions & restart the application `npm run dev`
11. Observe that things now break with errors

## Errors (unexpected)

At this point we get one of two errors, I am unable to replicate both consistently but removing the reactRouterDevTools plugin stops the error. In addition, the code (a non-trivial example from above) has worked for months before the migration to React Router from Remix.

### 1. `Cannot read properties of undefined (reading 'request')`

```
Oops!
Cannot read properties of undefined (reading 'request')

TypeError: Cannot read properties of undefined (reading 'request')
    at Module.<anonymous> (file:///.../dev/my-react-router-app/node_modules/react-router-devtools/dist/server.js:312:43)
    at /...dev/my-react-router-app/app/routes/home.tsx:9:17
    at file:///...dev/my-react-router-app/node_modules/react-router-devtools/dist/context.js:123:21
    at file:///...dev/my-react-router-app/node_modules/react-router-devtools/dist/server.js:311:20
    at callRouteHandler (/...dev/my-react-router-app/node_modules/react-router/dist/production/index.js:8629:22)
    at commonRoute.loader (/...dev/my-react-router-app/node_modules/react-router/dist/production/index.js:8741:25)
    at actualHandler (/...dev/my-react-router-app/node_modules/react-router/dist/production/index.js:3532:14)
    at /...dev/my-react-router-app/node_modules/react-router/dist/production/index.js:3543:91
    at runHandler (/...dev/my-react-router-app/node_modules/react-router/dist/production/index.js:3548:7)
    at callLoaderOrAction (/...dev/my-react-router-app/node_modules/react-router/dist/production/index.js:3593:22)
    at Object.resolve (/...dev/my-react-router-app/node_modules/react-router/dist/production/index.js:3488:27)
    at /...dev/my-react-router-app/node_modules/react-router/dist/production/index.js:3471:62
```

![Screenshot 2024-11-27 at 9 57 24 AM](https://github.com/user-attachments/assets/682eb0d5-f10a-4bc8-b124-7a0d8b504b3a)

### 2. `SyntaxError: Identifier 'loader' has already been declared`

```
react-router dev

Re-optimizing dependencies because vite config has changed
  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
9:53:00 am [vite] Error when evaluating SSR module /app/utils/example.server.ts:
|- SyntaxError: Identifier 'loader' has already been declared
    at new AsyncFunction (<anonymous>)
    at instantiateModule (file:///.../dev/ci-demo/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52963:24)

9:53:00 am [vite] Error when evaluating SSR module /app/routes/layout.tsx:
|- SyntaxError: Identifier 'loader' has already been declared
    at new AsyncFunction (<anonymous>)
    at instantiateModule (file:///.../dev/ci-demo/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52963:24)

9:53:00 am [vite] Error when evaluating SSR module /app/routes/layout.tsx?route-entry=1:
|- SyntaxError: Identifier 'loader' has already been declared
    at new AsyncFunction (<anonymous>)
    at instantiateModule (file:///.../dev/ci-demo/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52963:24)

9:53:00 am [vite] Error when evaluating SSR module virtual:react-router/server-build:
|- SyntaxError: Identifier 'loader' has already been declared
    at new AsyncFunction (<anonymous>)
    at instantiateModule (file:///.../dev/ci-demo/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52963:24)

9:53:00 am [vite] Internal server error: Identifier 'loader' has already been declared
      at new AsyncFunction (<anonymous>)
      at instantiateModule (file:///.../dev/ci-demo/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52963:24)
9:53:00 am [vite] Internal server error: Identifier 'loader' has already been declared
      at new AsyncFunction (<anonymous>)
      at instantiateModule (file:///.../dev/ci-demo/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52963:24) (x2)
```

![Screenshot 2024-11-27 at 9 53 08 AM](https://github.com/user-attachments/assets/9bdc364c-7521-4555-86a2-494698b53ff0)

### Other info (`package.json`/environment)

`package.json`
```json
{
  "name": "my-react-router-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "react-router build",
    "dev": "react-router dev",
    "start": "react-router-serve ./build/server/index.js",
    "typecheck": "react-router typegen && tsc --build --noEmit"
  },
  "dependencies": {
    "@react-router/node": "^7.0.1",
    "@react-router/serve": "^7.0.1",
    "isbot": "^5.1.17",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-router": "^7.0.1"
  },
  "devDependencies": {
    "@react-router/dev": "^7.0.1",
    "@types/node": "^20",
    "@types/react": "^18.3.12",
    "@types/react-dom": "^18.3.1",
    "autoprefixer": "^10.4.20",
    "postcss": "^8.4.49",
    "react-router-devtools": "^1.0.4",
    "tailwindcss": "^3.4.15",
    "typescript": "^5.6.3",
    "vite": "^5.4.11",
    "vite-tsconfig-paths": "^5.1.2"
  }
}
```

Environment info

```
  System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M3
    Memory: 100.84 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.local/state/fnm_multishells/32693_1732664333248/bin/node
    npm: 10.9.0 - ~/.local/state/fnm_multishells/32693_1732664333248/bin/npm
  Browsers:
    Edge: 131.0.2903.70
    Safari: 17.5
    Safari Technology Preview: 18.0
  npmPackages:
    @react-router/dev: ^7.0.1 => 7.0.1 
    @react-router/node: ^7.0.1 => 7.0.1 
    @react-router/serve: ^7.0.1 => 7.0.1 
    react-router: ^7.0.1 => 7.0.1 
    vite: ^5.4.11 => 5.4.11 
```

**Comment by AlemTuzlak** [comment]
I tihnk it's due to the way you use imported loaders, it probably throws my AST transofrmation off as I havent covered the import * as data from x, I'll take a look into this, the easiest solution for now would be to just do it any other way as I think I've covered all the other ones 😅

**Comment by AlemTuzlak** [comment]
For the errors number 2 about loaders being declared, could you add this plugin:
https://www.npmjs.com/package/vite-plugin-inspect
And check the layout for example and see what the transform by react-router-devtools looks like. That would be really helpful!

**Comment by lb-** [comment]
@AlemTuzlak I have had to do it on a different project, it's one of our actual projects but I have tried my best to remove a bunch of stuff from `layout` that's not relevant. The error still occurs.

Here's the screenshots, hopefully this is what you are after.

<img width="1779" alt="Screenshot 2024-11-28 at 8 23 22 PM" src="https://github.com/user-attachments/assets/e9f84531-809d-4ecd-b3f9-ef8446ce660e">
<img width="1783" alt="Screenshot 2024-11-28 at 8 23 11 PM" src="https://github.com/user-attachments/assets/5f993210-f8b2-4977-959b-a51388b024f6">
<img width="1785" alt="Screenshot 2024-11-28 at 8 23 00 PM" src="https://github.com/user-attachments/assets/0ea67689-93ef-4cf8-977c-440e77a28423">
<img width="1788" alt="Screenshot 2024-11-28 at 8 22 52 PM" src="https://github.com/user-attachments/assets/9e41f5a6-da43-494f-bd03-04be0f0d7f14">
<img width="1788" alt="Screenshot 2024-11-28 at 8 22 41 PM" src="https://github.com/user-attachments/assets/6f3c1935-0915-40b4-9611-5e468a054467">


```
  System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M3
    Memory: 57.89 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.local/state/fnm_multishells/77693_1732789440984/bin/node
    npm: 10.9.0 - ~/.local/state/fnm_multishells/77693_1732789440984/bin/npm
  Browsers:
    Edge: 131.0.2903.70
    Safari: 17.5
    Safari Technology Preview: 18.0
  npmPackages:
    @react-router/dev: 7.0.1 => 7.0.1 
    @react-router/express: 7.0.1 => 7.0.1 
    @react-router/node: 7.0.1 => 7.0.1 
    @react-router/remix-routes-option-adapter: 7.0.1 => 7.0.1 
    react-router: 7.0.1 => 7.0.1 
    vite: 5.4.11 => 5.4.11 
```

**Comment by AlemTuzlak** [comment]
@lb- Thank you so much, I've figured out the root cause of this, unfortunately I can't properly fix it YET as I'm waiting for the react-router team to drop support for config resolution to know precisely what is a route and what isn't. But until that happens I'll drop a fix that will remove this problem completely, but the fix relies on the fact that you haveyour routes under `app/routes`

**Comment by AlemTuzlak** [comment]
Just dropped v1.0.5!

**Comment by lb-** [comment]
Thank you, I will give it a go @AlemTuzlak

**Comment by rmichalak** [comment]
I think I may be hitting a similar problem @AlemTuzlak .
In my case we are importing `action`/`loader` from a separate file and then we are exporting it from a route file.
The error is:
```
[plugin:react-router:route-exports] Identifier 'loader' has already been declared. (13:13)

11 |  import { loader } from "./loader";
12 |  export { loader as _loader };
13 |  export const loader = _withLoaderContextWrapper(_loader, "routes/<some-route>");
                              ^
```
I'm using version `1.1.10`

**Comment by AlemTuzlak** [comment]
@rmichalak can you please create a new issue with a minimum repro, i'll fix it asap

**Comment by rmichalak** [comment]
@AlemTuzlak https://github.com/forge-42/react-router-devtools/issues/203
